site_name: 'SpotifyAPI-NET'
theme_dir: 'mytheme'
pages:
  - 'Home': 'index.md'
  - 'SpotifyWebAPI':
    - 'Getting started': 'SpotifyWebAPI/gettingstarted.md'
    - 'Examples': 'SpotifyWebAPI/examples.md'
    - 'Authentication': 'SpotifyWebAPI/auth.md'
    - '- Albums': 'SpotifyWebAPI/albums.md'
    - '- Artists': 'SpotifyWebAPI/artists.md'
    - '- Browse': 'SpotifyWebAPI/browse.md'
    - '- Follow': 'SpotifyWebAPI/follow.md'
    - '- Library': 'SpotifyWebAPI/library.md'
    - '- Player': 'SpotifyWebAPI/player.md'
    - '- Playlists': 'SpotifyWebAPI/playlists.md'
    - '- Profiles': 'SpotifyWebAPI/profiles.md'
    - '- Search': 'SpotifyWebAPI/search.md'
    - '- Tracks': 'SpotifyWebAPI/tracks.md'
    - '- Util': 'SpotifyWebAPI/util.md'
  - 'SpotifyLocalAPI': 'SpotifyLocalAPI/index.md'
repo_url: 'https://github.com/JohnnyCrazy/SpotifyAPI-NET'
site_author: 'JohnnyCrazy'
site_description: 'API Docs for SpotifyAPI-NET'
extra_javascript:
  - 'highlight.js'
markdown_extensions:
  - sane_lists
